setwd("/usr/people/groote/ThunderstormPostProcessingv1/ELRres")
data=read.csv("ELR_scores_VT_1800_LT_1_npred_111.csv")
data2=read.csv("ELR_CRPSscores_VT_1800_LT_1_npred_111.csv")
thres = c(2.1,2.5,3.0)^4
library(dplyr)
data <- filter(data, threshold %in% thres)
result <- data %>% group_by(numpredictors) %>% summarise(mean(ss_9fold),mean(ss_years))
print(result)
setwd("/usr/people/groote/ThunderstormPostProcessingv1/rangerres")
datarangerthres=read.csv("qrf_thresholds_ss_imp_newrandom_VT_0006_LT_1.csv")
datarangerhtres <- filter(datarangerthres, threshold %in% thres)
resultrangerthres <- datarangerthres %>% group_by(npred, mtry, min_n_size) %>% summarise(mean(bs))
value=resultrangerthres[max(as.numeric(resultrangerthres$'mean(bs)'==max(resultrangerthres$'mean(bs)'))*seq(1,nrow(resultrangerthres))),]
print(value)
setwd("/usr/people/groote/ThunderstormPostProcessingv1/rangerres")
datarangeryesno=read.csv("qrf_ss_imp_newrandom_VT_1800_LT_6.csv")
resultrangeryesno <- datarangeryesno %>% group_by(npred, mtry, min_n_size) %>% summarise(mean(bs))
print(sum(as.numeric(resultrangeryesno$'mean(bs)'==max(resultrangeryesno$'mean(bs)'))))
value2=resultrangeryesno[max(as.numeric(resultrangeryesno$'mean(bs)'==max(resultrangeryesno$'mean(bs)'))*seq(1,nrow(resultrangeryesno))),]
print(value2)
setwd("/usr/people/groote/ThunderstormPostProcessingv1/LRres")
dataLR=read.csv("LR_scores_9fold_VT_0612_LT_5npred_111.csv")
resultLR <- dataLR %>% group_by(npred) %>% summarise(mean(bs))
print(resultLR)
